version: "3.9"
services:
  app:
    image: openjdk:21
    command: sh -c "./mvnw package && java -jar target/*.jar"
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mongo
  mongo:
    build:
      context: mongoDb
    restart: always
volumes:
  mongo_data: { }